import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "RoomFlip.io terms of service. Understand the rules and guidelines for using our free AI interior design tool.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0f] text-white">
      <div className="max-w-3xl mx-auto px-6 py-24">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-slate-500 mb-12">Last updated: March 6, 2026</p>

        <div className="space-y-8 text-slate-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using RoomFlip.io (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service. We reserve the right to modify these terms at any time, and your continued use of the Service constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              RoomFlip.io is a free AI-powered interior design tool that allows users to upload photos of their rooms and receive AI-generated redesigns in various styles. The Service is provided &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. User-Uploaded Content</h2>
            <p className="mb-3">By uploading photos to RoomFlip.io, you represent and warrant that:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>You own the rights to the images you upload, or have permission to use them</li>
              <li>Your uploaded content does not infringe on any third party&apos;s intellectual property rights</li>
              <li>Your uploaded content does not contain illegal, harmful, or offensive material</li>
              <li>You will not upload images containing personally identifiable information of others without their consent</li>
            </ul>
            <p className="mt-3">
              We do not claim ownership of your uploaded images. Your photos are processed transiently by our AI service and are not permanently stored on our servers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. AI-Generated Content</h2>
            <p>
              The redesigned room images generated by our AI are provided for personal, non-commercial inspiration purposes. While we strive for high-quality results, AI-generated designs are approximations and should not be used as professional architectural or interior design plans. We make no guarantees regarding the accuracy, feasibility, or safety of implementing any AI-suggested designs in real life.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Fair Use &amp; Usage Limits</h2>
            <p className="mb-3">To ensure fair access for all users, the following limits apply:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Each user is limited to 5 room redesigns per day</li>
              <li>Automated or programmatic access to the Service is prohibited</li>
              <li>Attempting to bypass usage limits is a violation of these terms</li>
              <li>We reserve the right to adjust usage limits at any time</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Prohibited Uses</h2>
            <p className="mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Upload illegal, harmful, threatening, abusive, or objectionable content</li>
              <li>Attempt to reverse-engineer, decompile, or hack the Service</li>
              <li>Use automated scripts, bots, or scrapers to access the Service</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Impersonate any person or entity</li>
              <li>Use the Service for any commercial purpose without our written consent</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
            <p>
              The RoomFlip.io website, its original content (excluding user-uploaded images), features, and functionality are owned by RoomFlip and are protected by international copyright, trademark, and other intellectual property laws. Our name, logo, and all related marks are trademarks of RoomFlip.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Advertisements</h2>
            <p>
              The Service displays advertisements through Google AdSense and may include affiliate links to third-party retailers. We are not responsible for the content of third-party advertisements or the products and services they promote. Clicking on advertisements or affiliate links may direct you to third-party websites that have their own terms and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Limitation of Liability</h2>
            <p>
              IN NO EVENT SHALL ROOMFLIP, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Termination</h2>
            <p>
              We reserve the right to terminate or suspend your access to the Service immediately, without prior notice, for any reason whatsoever, including without limitation if you breach these Terms of Service. Upon termination, your right to use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with applicable laws, without regard to conflict of law provisions. Any disputes arising from these terms shall be resolved through good-faith negotiation before pursuing other remedies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">13. Contact Us</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us at{" "}
              <a href="mailto:hello@roomflip.io" className="text-indigo-400 hover:underline">hello@roomflip.io</a>.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-white/10 text-center">
          <Link href="/" className="text-indigo-400 hover:underline text-sm">Back to RoomFlip.io</Link>
        </div>
      </div>
    </main>
  );
}
